#Analisis de tuberculosis

**Cargar los datos**

In [ ]:
#paquetes para manipular datos
import pandas as pd
import numpy as np

pd.set_option('display.max_rows', None)
pd.set_option('display.max_colums', None)

OptionError: No such keys(s): 'display.max_colums'

In [ ]:
#paquetes para conectarse  Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
pop = pd.read_csv("/content/drive/MyDrive/Data/population.csv")
pop.head()

       country  year  population
0  Afghanistan  1995    17586073
1  Afghanistan  1996    18415307
2  Afghanistan  1997    19021226
3  Afghanistan  1998    19496836
4  Afghanistan  1999    19987071

In [ ]:
who= pd.read_csv("/content/drive/MyDrive/Data/who.csv")
who.head()

,country,iso2,iso3,year,new_sp_m014,new_sp_m1524,new_sp_m2534,new_sp_m3544,new_sp_m4554,new_sp_m5564,...,newrel_m4554,newrel_m5564,newrel_m65,newrel_f014,newrel_f1524,newrel_f2534,newrel_f3544,newrel_f4554,newrel_f5564,newrel_f65
0,Afghanistan,AF,AFG,1980,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AF,AFG,1981,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AF,AFG,1982,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,AF,AFG,1983,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,AF,AFG,1984,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#Limpieza y manipulación de datos

##Explorar los valores nulos faltantes N/A

In [ ]:
#Cuantos valores faltantes hay por columna
who.isna().sum()

country            0
iso2              34
iso3               0
year               0
new_sp_m014     4067
new_sp_m1524    4031
new_sp_m2534    4034
new_sp_m3544    4021
new_sp_m4554    4017
new_sp_m5564    4022
new_sp_m65      4031
new_sp_f014     4066
new_sp_f1524    4046
new_sp_f2534    4040
new_sp_f3544    4041
new_sp_f4554    4036
new_sp_f5564    4045
new_sp_f65      4043
new_sn_m014     6195
new_sn_m1524    6210
new_sn_m2534    6218
new_sn_m3544    6215
new_sn_m4554    6213
new_sn_m5564    6219
new_sn_m65      6220
new_sn_f014     6200
new_sn_f1524    6218
new_sn_f2534    6224
new_sn_f3544    6220
new_sn_f4554    6222
new_sn_f5564    6223
new_sn_f65      6221
new_ep_m014     6202
new_ep_m1524    6214
new_ep_m2534    6220
new_ep_m3544    6216
new_ep_m4554    6220
new_ep_m5564    6225
new_ep_m65      6222
new_ep_f014     6208
new_ep_f1524    6219
new_ep_f2534    6219
new_ep_f3544    6219
new_ep_f4554    6223
new_ep_f5564    6223
new_ep_f65      6226
newrel_m014     7050
newrel_m1524    7058
newrel_m2534    7057
newrel_m3544    7056
newrel_m4554    7056
newrel_m5564    7055
newrel_m65      7058
newrel_f014     7050
newrel_f1524    7056
newrel_f2534    7058
newrel_f3544    7057
newrel_f4554    7057
newrel_f5564    7057
newrel_f65      7055
dtype: int64

In [ ]:
#Calcular los valores faltantes en la columna iso2
who[who.iso2.isna()]

,country,iso2,iso3,year,new_sp_m014,new_sp_m1524,new_sp_m2534,new_sp_m3544,new_sp_m4554,new_sp_m5564,...,newrel_m4554,newrel_m5564,newrel_m65,newrel_f014,newrel_f1524,newrel_f2534,newrel_f3544,newrel_f4554,newrel_f5564,newrel_f65
4369,Namibia,NaN,NAM,1980,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4370,Namibia,NaN,NAM,1981,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4371,Namibia,NaN,NAM,1982,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4372,Namibia,NaN,NAM,1983,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4373,Namibia,NaN,NAM,1984,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4374,Namibia,NaN,NAM,1985,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4375,Namibia,NaN,NAM,1986,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4376,Namibia,NaN,NAM,1987,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4377,Namibia,NaN,NAM,1988,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4378,Namibia,NaN,NAM,1989,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4379,Namibia,NaN,NAM,1990,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4380,Namibia,NaN,NAM,1991,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4381,Namibia,NaN,NAM,1992,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4382,Namibia,NaN,NAM,1993,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4383,Namibia,NaN,NAM,1994,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4384,Namibia,NaN,NAM,1995,0.0,68.0,235.0,113.0,55.0,21.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4385,Namibia,NaN,NAM,1996,16.0,205.0,613.0,472.0,230.0,137.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4386,Namibia,NaN,NAM,1997,18.0,232.0,791.0,479.0,296.0,161.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4387,Namibia,NaN,NAM,1998,21.0,270.0,816.0,541.0,267.0,148.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4388,Namibia,NaN,NAM,1999,20.0,247.0,908.0,613.0,260.0,135.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4389,Namibia,NaN,NAM,2000,18.0,269.0,874.0,665.0,300.0,147.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4390,Namibia,NaN,NAM,2001,20.0,322.0,993.0,732.0,318.0,150.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4391,Namibia,NaN,NAM,2002,19.0,301.0,1033.0,750.0,326.0,146.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4392,Namibia,NaN,NAM,2003,31.0,364.0,1109.0,838.0,419.0,196.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4393,Namibia,NaN,NAM,2004,31.0,319.0,1092.0,866.0,371.0,159.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4394,Namibia,NaN,NAM,2005,98.0,355.0,1027.0,874.0,365.0,146.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4395,Namibia,NaN,NAM,2006,86.0,347.0,1052.0,799.0,386.0,174.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4396,Namibia,NaN,NAM,2007,57.0,370.0,1018.0,786.0,346.0,149.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4397,Namibia,NaN,NAM,2008,30.0,387.0,1033.0,757.0,346.0,149.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4398,Namibia,NaN,NAM,2009,41.0,357.0,936.0,689.0,348.0,166.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4399,Namibia,NaN,NAM,2010,36.0,359.0,852.0,680.0,287.0,146.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4400,Namibia,NaN,NAM,2011,48.0,337.0,844.0,660.0,361.0,152.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4401,Namibia,NaN,NAM,2012,61.0,358.0,810.0,686.0,292.0,157.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4402,Namibia,NaN,NAM,2013,NaN,NaN,NaN,NaN,NaN,NaN,...,723.0,392.0,309.0,491.0,688.0,1137.0,747.0,408.0,220.0,202.0

In [ ]:
#Los valores NA se deben a que el iso2 de namibia es "NA", y pandas lo tomocomo un valor

who.loc[who.country == "namibia", "iso2"] = "NA"

In [ ]:
#Los datos columna A de casos con valores faltantes van a tener un valor defaut de cero
who.fillna(0, inplace = True)

In [ ]:
#Cuantos valores faltantes hay por columna en la tabla pop
pop.isna().sum()

country       0
year          0
population    0
dtype: int64

In [ ]:
#¿Como puedo comvertir columnas en filas utilizando pandas? Existe la función melt
#Buscar la función melt en la documentación oficial
#Tenga una tabla de esta estructura
#Country | Year | Col1 | Col2
#Namidia | 2000 | 100 | 200
who2 = who.melt (id_vars=["country", "iso2", "iso3", "year"])
who2.head (15)

        country iso2 iso3  year     variable  value
0   Afghanistan   AF  AFG  1980  new_sp_m014    0.0
1   Afghanistan   AF  AFG  1981  new_sp_m014    0.0
2   Afghanistan   AF  AFG  1982  new_sp_m014    0.0
3   Afghanistan   AF  AFG  1983  new_sp_m014    0.0
4   Afghanistan   AF  AFG  1984  new_sp_m014    0.0
5   Afghanistan   AF  AFG  1985  new_sp_m014    0.0
6   Afghanistan   AF  AFG  1986  new_sp_m014    0.0
7   Afghanistan   AF  AFG  1987  new_sp_m014    0.0
8   Afghanistan   AF  AFG  1988  new_sp_m014    0.0
9   Afghanistan   AF  AFG  1989  new_sp_m014    0.0
10  Afghanistan   AF  AFG  1990  new_sp_m014    0.0
11  Afghanistan   AF  AFG  1991  new_sp_m014    0.0
12  Afghanistan   AF  AFG  1992  new_sp_m014    0.0
13  Afghanistan   AF  AFG  1993  new_sp_m014    0.0
14  Afghanistan   AF  AFG  1994  new_sp_m014    0.0

In [ ]:
from ast import Return
#Crear una columna que contega el genero (masculino/femenino)
#Crear una función de payton que contenga las reglas
def asignar_genero():
  if "m" in valor:
    return "Masculino"
  else:
      return "femenino"

In [ ]:
def asignar_genero(valor):
  if "m" in str(valor):
    return "Masculino"
  elif "f" in str(valor):
    return "Femenino"
  else:
    return "No_definido" # Consider how to handle cases where neither 'm' nor 'f' is present

who2["genero"] = who2["variable"].apply(asignar_genero)
who2.head(100)

        country iso2 iso3  year     variable  value     genero
0   Afghanistan   AF  AFG  1980  new_sp_m014    0.0  Masculino
1   Afghanistan   AF  AFG  1981  new_sp_m014    0.0  Masculino
2   Afghanistan   AF  AFG  1982  new_sp_m014    0.0  Masculino
3   Afghanistan   AF  AFG  1983  new_sp_m014    0.0  Masculino
4   Afghanistan   AF  AFG  1984  new_sp_m014    0.0  Masculino
5   Afghanistan   AF  AFG  1985  new_sp_m014    0.0  Masculino
6   Afghanistan   AF  AFG  1986  new_sp_m014    0.0  Masculino
7   Afghanistan   AF  AFG  1987  new_sp_m014    0.0  Masculino
8   Afghanistan   AF  AFG  1988  new_sp_m014    0.0  Masculino
9   Afghanistan   AF  AFG  1989  new_sp_m014    0.0  Masculino
10  Afghanistan   AF  AFG  1990  new_sp_m014    0.0  Masculino
11  Afghanistan   AF  AFG  1991  new_sp_m014    0.0  Masculino
12  Afghanistan   AF  AFG  1992  new_sp_m014    0.0  Masculino
13  Afghanistan   AF  AFG  1993  new_sp_m014    0.0  Masculino
14  Afghanistan   AF  AFG  1994  new_sp_m014    0.0  Masculino
15  Afghanistan   AF  AFG  1995  new_sp_m014    0.0  Masculino
16  Afghanistan   AF  AFG  1996  new_sp_m014    0.0  Masculino
17  Afghanistan   AF  AFG  1997  new_sp_m014    0.0  Masculino
18  Afghanistan   AF  AFG  1998  new_sp_m014   30.0  Masculino
19  Afghanistan   AF  AFG  1999  new_sp_m014    8.0  Masculino
20  Afghanistan   AF  AFG  2000  new_sp_m014   52.0  Masculino
21  Afghanistan   AF  AFG  2001  new_sp_m014  129.0  Masculino
22  Afghanistan   AF  AFG  2002  new_sp_m014   90.0  Masculino
23  Afghanistan   AF  AFG  2003  new_sp_m014  127.0  Masculino
24  Afghanistan   AF  AFG  2004  new_sp_m014  139.0  Masculino
25  Afghanistan   AF  AFG  2005  new_sp_m014  151.0  Masculino
26  Afghanistan   AF  AFG  2006  new_sp_m014  193.0  Masculino
27  Afghanistan   AF  AFG  2007  new_sp_m014  186.0  Masculino
28  Afghanistan   AF  AFG  2008  new_sp_m014  187.0  Masculino
29  Afghanistan   AF  AFG  2009  new_sp_m014  200.0  Masculino
30  Afghanistan   AF  AFG  2010  new_sp_m014  197.0  Masculino
31  Afghanistan   AF  AFG  2011  new_sp_m014  204.0  Masculino
32  Afghanistan   AF  AFG  2012  new_sp_m014  188.0  Masculino
33  Afghanistan   AF  AFG  2013  new_sp_m014    0.0  Masculino
34      Albania   AL  ALB  1980  new_sp_m014    0.0  Masculino
35      Albania   AL  ALB  1981  new_sp_m014    0.0  Masculino
36      Albania   AL  ALB  1982  new_sp_m014    0.0  Masculino
37      Albania   AL  ALB  1983  new_sp_m014    0.0  Masculino
38      Albania   AL  ALB  1984  new_sp_m014    0.0  Masculino
39      Albania   AL  ALB  1985  new_sp_m014    0.0  Masculino
40      Albania   AL  ALB  1986  new_sp_m014    0.0  Masculino
41      Albania   AL  ALB  1987  new_sp_m014    0.0  Masculino
42      Albania   AL  ALB  1988  new_sp_m014    0.0  Masculino
43      Albania   AL  ALB  1989  new_sp_m014    0.0  Masculino
44      Albania   AL  ALB  1990  new_sp_m014    0.0  Masculino
45      Albania   AL  ALB  1991  new_sp_m014    0.0  Masculino
46      Albania   AL  ALB  1992  new_sp_m014    0.0  Masculino
47      Albania   AL  ALB  1993  new_sp_m014    0.0  Masculino
48      Albania   AL  ALB  1994  new_sp_m014    0.0  Masculino
49      Albania   AL  ALB  1995  new_sp_m014    0.0  Masculino
50      Albania   AL  ALB  1996  new_sp_m014    0.0  Masculino
51      Albania   AL  ALB  1997  new_sp_m014    0.0  Masculino
52      Albania   AL  ALB  1998  new_sp_m014    1.0  Masculino
53      Albania   AL  ALB  1999  new_sp_m014    0.0  Masculino
54      Albania   AL  ALB  2000  new_sp_m014    2.0  Masculino
55      Albania   AL  ALB  2001  new_sp_m014    3.0  Masculino
56      Albania   AL  ALB  2002  new_sp_m014    0.0  Masculino
57      Albania   AL  ALB  2003  new_sp_m014    0.0  Masculino
58      Albania   AL  ALB  2004  new_sp_m014    5.0  Masculino
59      Albania   AL  ALB  2005  new_sp_m014    0.0  Masculino
60      Albania   AL  ALB  2006  new_sp_m014    5.0  Masculino
61      Albania   AL  ALB  2007  new_sp_m014    0.0  Masculino
62      Albania   AL  ALB  2008  new_sp_m014    1.0  Masculino
63      Albania   AL  ALB  2009  new_sp_m014    0.0  Masculino
64      Albania   AL  ALB  2010  new_sp_m014    0.0  Masculino
65      Albania   AL  ALB  2011  new_sp_m014    0.0  Masculino
66      Albania   AL  ALB  2012  new_sp_m014    0.0  Masculino
67      Albania   AL  ALB  2013  new_sp_m014    0.0  Masculino
68      Algeria   DZ  DZA  1980  new_sp_m014    0.0  Masculino
69      Algeria   DZ  DZA  1981  new_sp_m014    0.0  Masculino
70      Algeria   DZ  DZA  1982  new_sp_m014    0.0  Masculino
71      Algeria   DZ  DZA  1983  new_sp_m014    0.0  Masculino
72      Algeria   DZ  DZA  1984  new_sp_m014    0.0  Masculino
73      Algeria   DZ  DZA  1985  new_sp_m014    0.0  Masculino
74      Algeria   DZ  DZA  1986  new_sp_m014    0.0  Masculino
75      Algeria   DZ  DZA  1987  new_sp_m014    0.0  Masculino
76      Algeria   DZ  DZA  1988  new_sp_m014    0.0  Masculino
77      Algeria   DZ  DZA  1989  new_sp_m014    0.0  Masculino
78      Algeria   DZ  DZA  1990  new_sp_m014    0.0  Masculino
79      Algeria   DZ  DZA  1991  new_sp_m014    0.0  Masculino
80      Algeria   DZ  DZA  1992  new_sp_m014    0.0  Masculino
81      Algeria   DZ  DZA  1993  new_sp_m014    0.0  Masculino
82      Algeria   DZ  DZA  1994  new_sp_m014    0.0  Masculino
83      Algeria   DZ  DZA  1995  new_sp_m014    0.0  Masculino
84      Algeria   DZ  DZA  1996  new_sp_m014    0.0  Masculino
85      Algeria   DZ  DZA  1997  new_sp_m014  659.0  Masculino
86      Algeria   DZ  DZA  1998  new_sp_m014    0.0  Masculino
87      Algeria   DZ  DZA  1999  new_sp_m014   40.0  Masculino
88      Algeria   DZ  DZA  2000  new_sp_m014   59.0  Masculino
89      Algeria   DZ  DZA  2001  new_sp_m014   41.0  Masculino
90      Algeria   DZ  DZA  2002  new_sp_m014   39.0  Masculino
91      Algeria   DZ  DZA  2003  new_sp_m014   40.0  Masculino
92      Algeria   DZ  DZA  2004  new_sp_m014   63.0  Masculino
93      Algeria   DZ  DZA  2005  new_sp_m014   53.0  Masculino
94      Algeria   DZ  DZA  2006  new_sp_m014   41.0  Masculino
95      Algeria   DZ  DZA  2007  new_sp_m014   95.0  Masculino
96      Algeria   DZ  DZA  2008  new_sp_m014   99.0  Masculino
97      Algeria   DZ  DZA  2009  new_sp_m014   43.0  Masculino
98      Algeria   DZ  DZA  2010  new_sp_m014   52.0  Masculino
99      Algeria   DZ  DZA  2011  new_sp_m014   42.0  Masculino

In [ ]:
def asignar_metodo(valor):
  if "rel" in valor:
    return "relapse"
  elif "sn" in valor:
    return "negative pulmonary smear"
  elif "sp" in valor:
    return "positive pulmonary smear"
  elif "ep" in valor:
    return "extrapulmonary"
  else:
    return "to define"

In [ ]:
who2["metodo"]=who2 ["variable"].apply(asignar_metodo)
who2.head()

,country,iso2,iso3,year,variable,value,genero,metodo
0,Afghanistan,AF,AFG,1980,new_sp_m014,0.0,Masculino,positive pulmonary smear
1,Afghanistan,AF,AFG,1981,new_sp_m014,0.0,Masculino,positive pulmonary smear
2,Afghanistan,AF,AFG,1982,new_sp_m014,0.0,Masculino,positive pulmonary smear
3,Afghanistan,AF,AFG,1983,new_sp_m014,0.0,Masculino,positive pulmonary smear
4,Afghanistan,AF,AFG,1984,new_sp_m014,0.0,Masculino,positive pulmonary smear

In [ ]:
# age group (014 = 0-14 yrs of age, 1524 = 15-24, 2534 = 25-34, 3544 = 35-44 years of age, 4554 = 45-54, 5564 = 55-64, 65 = 65 years or older).
def asignar_grupoedad(valor):
  if "014" in valor:
    return "0-14"
  elif "1524" in valor:
    return "15-24"
  elif "2534" in valor:
    return "25-34"
  elif "3544" in valor:
    return "35-44"
  elif "4554" in valor:
    return "45-54"
  elif "5564" in valor:
    return "55-64"
  else:
    return "65+"

In [ ]:
who2["grupoedad"] = who2["variable"].apply(asignar_grupoedad)
who2.head()

,country,iso2,iso3,year,variable,value,genero,metodo,grupoedad
0,Afghanistan,AF,AFG,1980,new_sp_m014,0.0,Masculino,positive pulmonary smear,0-14
1,Afghanistan,AF,AFG,1981,new_sp_m014,0.0,Masculino,positive pulmonary smear,0-14
2,Afghanistan,AF,AFG,1982,new_sp_m014,0.0,Masculino,positive pulmonary smear,0-14
3,Afghanistan,AF,AFG,1983,new_sp_m014,0.0,Masculino,positive pulmonary smear,0-14
4,Afghanistan,AF,AFG,1984,new_sp_m014,0.0,Masculino,positive pulmonary smear,0-14

In [ ]:
# remover la columna variable
who2.drop(columns=["variable"], inplace=True)

In [ ]:
# renombrar la columna value a casos
who2.rename(columns={"value":"cases"}, inplace=True)

In [ ]:
who2.head()

,country,iso2,iso3,year,cases,genero,metodo,grupoedad
0,Afghanistan,AF,AFG,1980,0.0,Masculino,positive pulmonary smear,0-14
1,Afghanistan,AF,AFG,1981,0.0,Masculino,positive pulmonary smear,0-14
2,Afghanistan,AF,AFG,1982,0.0,Masculino,positive pulmonary smear,0-14
3,Afghanistan,AF,AFG,1983,0.0,Masculino,positive pulmonary smear,0-14
4,Afghanistan,AF,AFG,1984,0.0,Masculino,positive pulmonary smear,0-14

In [ ]:
# Traer el dato de la poblacion total
df = pd.merge(who2, pop, on=["country", "year"], how="inner")
df.head()

,country,iso2,iso3,year,cases,genero,metodo,grupoedad,population
0,Afghanistan,AF,AFG,1995,0.0,Masculino,positive pulmonary smear,0-14,17586073
1,Afghanistan,AF,AFG,1996,0.0,Masculino,positive pulmonary smear,0-14,18415307
2,Afghanistan,AF,AFG,1997,0.0,Masculino,positive pulmonary smear,0-14,19021226
3,Afghanistan,AF,AFG,1998,30.0,Masculino,positive pulmonary smear,0-14,19496836
4,Afghanistan,AF,AFG,1999,8.0,Masculino,positive pulmonary smear,0-14,19987071

In [ ]:
# Como guardar la tabla "df" como un archivo csv
df.to_csv("tuberculosis.csv") # se guarda en la carpeta de la sesion
df.to_csv("/content/drive/MyDrive/Data/tuberculosis.csv") # se guarda en el drive